[package]
name = "guess_the_word"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.2" # Добавляем в зависимости сторонний контейнер